# Generated by Django 2.0 on 2019-07-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=50)),
                ('location', models.CharField(default=True, max_length=50)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('description', models.CharField(max_length=150)),
                ('speakers', models.CharField(max_length=200)),
            ],
        ),
    ]
