# Generated by Django 2.0 on 2019-07-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='keynoteSpeakers',
            new_name='speakers',
        ),
    ]
