# Generated by Django 2.0 on 2019-07-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190722_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='endtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='startdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='starttime',
            field=models.TimeField(),
        ),
    ]
