# Generated by Django 2.0 on 2019-07-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190722_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startdate',
        ),
        migrations.AlterField(
            model_name='event',
            name='endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
