# Generated by Django 2.0 on 2019-07-24 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100)),
                ('userFirstName', models.CharField(default='', max_length=30)),
                ('userLastName', models.CharField(default='', max_length=30)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userContact', models.CharField(default='', max_length=20)),
                ('userAddress', models.CharField(default='', max_length=30)),
                ('userCity', models.CharField(default='', max_length=30)),
                ('userState', models.CharField(default='', max_length=30)),
                ('userZipcode', models.CharField(default='', max_length=30)),
                ('userPassportID', models.CharField(default='', max_length=30)),
                ('userNationalID', models.CharField(default='', max_length=30)),
                ('socialAccountTableUid', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(default='', max_length=30)),
                ('userImage', models.ImageField(blank=True, default='userImages/no-image.jpg', upload_to='userImages')),
                ('userSerialNo', models.IntegerField(default=0)),
                ('userCode', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('userRole', models.CharField(default='user', max_length=10)),
                ('userTableName', models.CharField(default='userProfile', max_length=30)),
            ],
        ),
    ]
